#!/usr/bin/env bash
__pre_map() {
  [[ -n "$BEFORE" ]] && eval "$BEFORE"
  [[ $WM == "bspwm" ]] && bspc rule -a $CLASS:$INSTANCE -o state=floating;
  [[ $WM == "awesome" ]] && awesome-client "$AWESOME_APPEND"
}
__post_map() {
  [[ $WM == "awesome" ]] && awesome-client "$AWESOME_REMOVE"
  [[ -n "$AFTER" ]] && eval "$AFTER"
}
__parse_dimension() {
  W=$(awk -F+ '{print $1}' <<< $GEO | awk -Fx '{print $1}' | tee $APP_CACHE)
  H=$(awk -F+ '{print $1}' <<< $GEO | awk -Fx '{print $2}' | tee -a $APP_CACHE)
  X=$(awk -F+ '{print $2}' <<< $GEO | tee -a $APP_CACHE)
  Y=$(awk -F+ '{print $3}' <<< $GEO | tee -a $APP_CACHE)
}

_win_visible() { [[ $(xwininfo -id "$WID" 2> /dev/null | gawk '/Map State/ {print $3}') == IsViewable ]]; }
_wid_expired() {
  wid_name=$(xprop -id $WID 2>/dev/null | grep "^WM_NAME(.*)" 2>/dev/null | awk '{print $3}' | tr -d ',"')
  [[ -z $wid_name ]] && return 0; [[ "$wid_name" = "$NAME" ]] && return 1
  wid_class=$(xprop -id $WID 2>/dev/null | grep "WM_CLASS(STRING)" 2>/dev/null | awk '{print $NF}' | tr -d ',"')
  wid_instance=$(xprop -id $WID 2>/dev/null | grep "WM_CLASS(STRING)" 2>/dev/null | awk '{print $3}' | tr -d ',"')
  [[ "$wid_class" = "$CLASS" ]] && [[ -z $INSTANCE ]] && return 1
  [[ "$wid_instance" = "$INSTANCE" ]] && return 1
}
_hide_window () { xdotool windowunmap $WID; }
_show_window() {
  __pre_map
  xdotool set_desktop_for_window "${1:-$WID}" "$(xdotool get_desktop)"
  w=$(sed -n 1p $APP_CACHE) h=$(sed -n 2p $APP_CACHE)
  x=$(sed -n 3p $APP_CACHE) y=$(sed -n 4p $APP_CACHE)
  xdotool windowmap ${1:-$WID} windowmove ${1:-$WID} $x $y windowsize ${1:-$WID} $w $h
  __post_map
}
_create_window() {
  __parse_dimension
  t_cmd=(alacritty --class $INSTANCE,$CLASS)
  [[ "$APP" == "dropterm" ]] || t_cmd+=("-e ${CMD[@]}")
  t_cmd=(`echo ${t_cmd[@]} | sed 's/\"/\\\"/g'`)
  g_cmd=(`echo ${CMD[@]} | sed 's/\"/\\\"/g'`)
  _intercept &
  $TERMINAL && eval "${t_cmd[@]} &" || eval "${g_cmd[@]} &"
}
_intercept() {
  __pre_map
  local wid timeout=1000 exceeded=false
  counter=0
  while true; do
    new_wid=$(eval ${SEARCH_CMD[@]})
    [[ -n $new_wid ]] && break
    [[ $counter -gt $timeout ]] && { exceeded=true; break; }
    sleep .01; counter=$((counter + 1))
  done
  $exceeded && log "Wait for $CLASS:${INTERCEPT_FROM:-$INSTANCE} timeout." && exit 1;
  wid=$new_wid; [[ -n $INTERCEPT_FROM ]] && xdotool set_window --classname $INSTANCE $wid
  _show_window $wid
  echo $wid >> $APP_CACHE
}

log() { echo "$@" >> $FLOATWIN/log; }
meta() {
  local id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK); id=${id##* }
  wm=$(xprop -notype -id "$id" _NET_WM_NAME | head -n 1); wm=${wm##* }; wm=${wm//\"/}
  echo $wm > $FLOATWIN/000META
}
toggle_or_create() {
  if _wid_expired; then _create_window
  elif _win_visible; then _hide_window
  else _show_window
  fi
}

FLOATWIN="$XDG_CACHE_HOME/floatwin"
TERMINAL=false
GEO=1920x1080+50+50
RESET=false
INTERCEPT=false

[[ -d "$FLOATWIN" ]] || mkdir -p $FLOATWIN
[[ -f "$FLOATWIN/000META" ]] || meta

while getopts "a:b:c:d:f:i:I:n:tr" opt; do
  case $opt in
    a) AFTER=$OPTARG;;
    b) BEFORE=$OPTARG;;
    c) CLASS=${OPTARG%:*}; INSTANCE=${OPTARG#*:};;
    d) GEO=$OPTARG;;
    f) INTERCEPT_FROM=$OPTARG;;
    i) INDEX=$OPTARG;;
    I) INTERCEPT=true; CLASS=${OPTARG%:*}; INSTANCE=${OPTARG#*:};;
    n) NAME=$OPTARG;;
    t) TERMINAL=true;;
    r) RESET=true;;
  esac
done
shift $((OPTIND -1))

WM=$(cat "$FLOATWIN/000META")
CMD="${@}"; [[ -z $CMD ]] && CMD="echo"
APP=${1:-dropterm}
$RESET && { rm -rf $FLOATWIN; echo "cache cleared."; exit 0; }
$TERMINAL && { CLASS=${CLASS:-$APP}; INSTANCE=${INSTANCE:-$CLASS}; }
[[ -n $INDEX ]] && INSTANCE=$INSTANCE.$INDEX
SEARCH_CMD=(xdo id -d)
[[ -n $CLASS ]] && { SEARCH_CMD+=("-N $CLASS"); rule_class="class={\"$CLASS\"},"; }
[[ -n $INSTANCE ]] && { SEARCH_CMD+=("-n $INSTANCE"); rule_instance="instance={\"$INSTANCE\"},"; }
[[ -n $NAME ]] && { SEARCH_CMD+=("-a $NAME"); rule_name="name={\"$NAME\"},"; }
AWESOME_APPEND="require('ruled').client.append_rule{id='floatwin',
rule_any={$rule_class$rule_instance$rule_name},properties={floating=true}}"
AWESOME_REMOVE="require('ruled').client.remove_rule('floatwin')"
APP_CACHE=$FLOATWIN/$APP.${INDEX:-0}
$INTERCEPT && { _intercept; exit 0; }
WID=$(tail -n 1 "$APP_CACHE" 2>/dev/null)
# echo ${SEARCH_CMD[@]}
toggle_or_create
